### PR TITLE
Redmine 2.x compatibility

### PR DESCRIPTION
**Pull request by jingoro**
Hi there,

Thanks for the plugin. I updated this so that it's compatible with Redmine 2.x.

John

### CODE REVIEW

**Comment by powdahound** [comment]
Nice. :) Is this change backwards compatible with older versions too?

**Comment by jingoro** [comment]
I didn't test it against older versions but I would be highly surprised if it worked.

I think it would be prudent to make a branch specifically for 2.x.

**Comment by powdahound** [comment]
I'll merge it in for now, and if we have reports of it breaking older versions I can come back and tag the commit before this as a 1x branch. Thanks for the improvements!

**Comment by vkotovv** [comment]
I can confirm that it works on Redmine 1.3.0

**Pull request merged**
